@extends('layouts.app')

@php
    $post = $post ?? null;
    $editing = $post !== null;
    $publishOption = old('action', $post?->status?->value === 'pending' ? 'schedule' : 'draft');
    $stepForField = ['project_id' => 1, 'platform' => 2, 'social_page_id' => 3, 'message' => 5, 'action' => 6, 'scheduled_date' => 6, 'scheduled_time' => 6, 'timezone' => 6];
    $initialStep = collect($errors->keys())->map(fn ($field) => $stepForField[$field] ?? (str_starts_with($field, 'media.') ? 5 : 7))->min() ?? 1;
@endphp
@section('title', $editing ? 'Edit Post' : 'Create Post')
@section('subtitle', 'A guided workflow for creating polished social content')

@section('content')
<form method="post" action="{{ $editing ? route('posts.update', $post) : route('posts.store') }}" enctype="multipart/form-data" id="post-wizard" novalidate>
    @csrf
    @if($editing) @method('PUT') @endif
    <input type="hidden" name="platform" id="platform" value="{{ old('platform', $post->platform ?? '') }}">
    <input type="hidden" name="action" id="action" value="{{ $publishOption }}">

    <div class="wizard-progress mb-4" aria-label="Create post progress">
        @foreach(['Project','Platform','Destination','Content','Creative','Publish','Review'] as $number => $label)
            <div class="wizard-progress-item" data-progress="{{ $number + 1 }}"><span>{{ $number + 1 }}</span><strong>{{ $label }}</strong></div>
        @endforeach
    </div>

    <div class="wizard-shell">
        <section class="wizard-step" data-step="1">
            <div class="wizard-step-heading"><span>Step 1</span><h2>Select Project</h2><p>Choose the workspace this post belongs to.</p></div>
            <label class="form-label" for="project_id">Project <span class="required-indicator">*</span></label>
            <select class="form-select form-select-lg @error('project_id') is-invalid @enderror" name="project_id" id="project_id" required><option value="">Select project</option>@foreach($projects as $item)<option value="{{ $item->id }}" @selected((int) old('project_id', $project?->id) === $item->id)>{{ $item->name }}</option>@endforeach</select>
            @error('project_id')<div class="invalid-feedback" id="project_id-error">{{ $message }}</div>@enderror
        </section>

        <section class="wizard-step d-none" data-step="2">
            <div class="wizard-step-heading"><span>Step 2</span><h2>Select Platform</h2><p>Choose where you want this content to appear.</p></div>
            <div class="form-label">Platform <span class="required-indicator">*</span></div>
            <div class="wizard-platform-grid @error('platform') is-invalid @enderror" id="platform-picker" aria-describedby="platform-error">@foreach(['facebook'=>'Facebook','instagram'=>'Instagram','linkedin'=>'LinkedIn','twitter'=>'X (Twitter)','tiktok'=>'TikTok','youtube'=>'YouTube'] as $key => $name)<button type="button" class="wizard-platform-card" data-platform="{{ $key }}"><span class="platform-dot platform-{{ $key }}"></span><strong>{{ $name }}</strong><small>Publish to {{ $name }}</small></button>@endforeach</div>
            <div class="invalid-feedback" id="platform-error">@error('platform'){{ $message }}@enderror</div>
        </section>

        <section class="wizard-step d-none" data-step="3">
            <div class="wizard-step-heading"><span>Step 3</span><h2>Select Page, Profile or Account</h2><p id="destination-help">Choose the connected destination for this post.</p></div>
            <label class="form-label" id="destination-label" for="social_page_id">Page / Profile <span class="required-indicator">*</span></label>
            <select class="form-select form-select-lg @error('social_page_id') is-invalid @enderror" name="social_page_id" id="social_page_id" required><option value="">Select profile/page</option>@foreach($pages as $page)<option value="{{ $page->id }}" data-provider="{{ $page->provider }}" data-instagram="{{ $page->instagram_business_id ? '1' : '0' }}" data-instagram-username="{{ $page->instagram_username }}" @selected((int) old('social_page_id', $post->social_page_id ?? 0) === $page->id)>{{ ucfirst($page->provider) }} - {{ $page->page_name }}{{ $page->instagram_username ? ' / @'.$page->instagram_username : '' }}</option>@endforeach</select>
            @error('social_page_id')<div class="invalid-feedback" id="social_page_id-error">{{ $message }}</div>@enderror
        </section>

        <section class="wizard-step d-none" data-step="4">
            <div class="wizard-step-heading"><span>Step 4</span><h2>Select Content Type</h2><p>Only formats supported by the selected platform are shown.</p></div>
            <div class="content-type-grid" id="content-types"></div><div class="guidelines-card mt-4" id="platform-guidelines"></div>
        </section>

        <section class="wizard-step d-none" data-step="5">
            <div class="wizard-step-heading"><span>Step 5</span><h2>Create Your Content</h2><p>Write your caption, add media, and check the live preview.</p></div>
            <div class="row g-4"><div class="col-lg-7"><label class="form-label d-flex justify-content-between" for="message">Caption <span class="required-indicator me-auto ms-1">*</span><span id="caption-counter" class="text-muted"></span></label><textarea class="form-control composer-text @error('message') is-invalid @enderror" id="message" name="message" maxlength="63206" required>{{ old('message', $post->message ?? '') }}</textarea>@error('message')<div class="invalid-feedback" id="message-error">{{ $message }}</div>@enderror<div class="composer-tools"><button type="button" class="btn btn-light btn-sm" data-insert="#"># Hashtag</button><button type="button" class="btn btn-light btn-sm" data-insert="@">@ Mention</button></div><label class="form-label mt-4">Upload Media</label><div class="upload-zone"><i class="bi bi-cloud-arrow-up"></i><div><strong>Drop images or videos here</strong><span>JPG, PNG, WEBP, GIF, MP4, MOV, AVI, WEBM</span></div><input class="form-control @error('media') is-invalid @enderror" id="media" type="file" name="media[]" multiple accept="image/*,video/*"></div>@error('media')<div class="invalid-feedback d-block" id="media-error">{{ $message }}</div>@enderror<div class="media-thumbnails mt-3" id="media-thumbnails">@if($editing) @foreach($post->media as $media)<span class="media-chip"><i class="bi bi-file-earmark"></i> {{ basename($media->path) }}</span>@endforeach @endif</div></div><div class="col-lg-5"><div class="live-preview"><div class="preview-label">Live preview</div><div class="preview-head"><span class="platform-dot" id="preview-dot"></span><strong id="preview-name">Your profile</strong></div><div id="preview-media" class="preview-media d-none"></div><p id="preview-message" class="mb-0 text-break">Your caption will appear here.</p></div></div></div>
        </section>

        <section class="wizard-step d-none" data-step="6">
            <div class="wizard-step-heading"><span>Step 6</span><h2>Select Publish Option</h2><p>Save it for later, schedule it, or publish immediately.</p></div>
            <div class="form-label">Publish Option <span class="required-indicator">*</span></div>
            <div class="publish-option-grid @error('action') is-invalid @enderror"><label><input type="radio" name="publish_option" value="draft" @checked($publishOption === 'draft')><span><i class="bi bi-save"></i><strong>Save Draft</strong><small>Keep editing later</small></span></label><label><input type="radio" name="publish_option" value="schedule" @checked($publishOption === 'schedule')><span><i class="bi bi-calendar-plus"></i><strong>Schedule</strong><small>Choose a future time</small></span></label><label><input type="radio" name="publish_option" value="publish" @checked($publishOption === 'publish')><span><i class="bi bi-send"></i><strong>Publish Now</strong><small>Send to the selected account</small></span></label></div>
            <div class="invalid-feedback" id="action-error">@error('action'){{ $message }}@enderror</div>
            <div id="schedule-fields" class="schedule-fields d-none mt-4"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="scheduled_date">Schedule Date <span class="required-indicator">*</span></label><input class="form-control @error('scheduled_date') is-invalid @enderror" id="scheduled_date" type="date" name="scheduled_date" value="{{ old('scheduled_date', isset($post?->scheduled_date) ? $post->scheduled_date->format('Y-m-d') : '') }}">@error('scheduled_date')<div class="invalid-feedback" id="scheduled_date-error">{{ $message }}</div>@enderror</div><div class="col-md-4"><label class="form-label" for="scheduled_time">Schedule Time <span class="required-indicator">*</span></label><input class="form-control @error('scheduled_time') is-invalid @enderror" id="scheduled_time" type="time" name="scheduled_time" value="{{ old('scheduled_time', !empty($post?->scheduled_time) ? \Carbon\Carbon::parse($post->scheduled_time)->format('H:i') : '') }}">@error('scheduled_time')<div class="invalid-feedback" id="scheduled_time-error">{{ $message }}</div>@enderror</div><div class="col-md-4"><label class="form-label" for="timezone">Timezone <span class="required-indicator">*</span></label><input class="form-control @error('timezone') is-invalid @enderror" id="timezone" list="timezone-options" name="timezone" value="{{ old('timezone', $post->timezone ?? auth()->user()->timezone ?? config('app.timezone')) }}" required><datalist id="timezone-options"><option value="UTC"><option value="America/New_York"><option value="America/Los_Angeles"><option value="Europe/London"><option value="Asia/Kolkata"><option value="Asia/Dubai"><option value="Asia/Singapore"></datalist>@error('timezone')<div class="invalid-feedback" id="timezone-error">{{ $message }}</div>@enderror</div></div><div class="time-card mt-3"><strong>Current time</strong><div id="local-time" class="small mt-1"></div><div id="utc-time" class="small"></div><p class="small text-muted mb-0 mt-2">All scheduled posts are stored internally in UTC and automatically published according to this timezone.</p></div></div>
        </section>

        <section class="wizard-step d-none" data-step="7"><div class="wizard-step-heading"><span>Step 7</span><h2>Review Summary</h2><p>Confirm the details before your post is saved or published.</p></div><div class="review-summary" id="review-summary"></div></section>
        <div class="wizard-footer"><button type="button" class="btn btn-outline-secondary d-none" id="previous-step">Back</button><button type="button" class="btn btn-primary" id="next-step">Continue</button><button type="submit" class="btn btn-primary d-none" id="submit-post">Finish</button></div>
    </div>
</form>
@endsection

@push('scripts')
<script>
const form=document.getElementById('post-wizard'),projectSelect=document.getElementById('project_id'),platform=document.getElementById('platform'),target=document.getElementById('social_page_id'),message=document.getElementById('message'),media=document.getElementById('media'),action=document.getElementById('action'),timezone=document.getElementById('timezone'),scheduledDate=document.getElementById('scheduled_date'),scheduledTime=document.getElementById('scheduled_time');let step={{ $initialStep }},projectPages=[];
const config={facebook:{limit:63206,types:['Post','Image','Video','Reel'],guide:'Recommended image: 1200 × 630. Videos up to 10GB.'},instagram:{limit:2200,types:['Image','Reel','Carousel'],guide:'Image: 1080 × 1080. Caption limit: 2,200 characters.'},linkedin:{limit:3000,types:['Post','Image','Video'],guide:'Character limit: 3,000.'},twitter:{limit:280,types:['Post','Image','Video'],guide:'Standard posts support up to 280 characters.'},tiktok:{limit:2200,types:['Video'],guide:'Use a 9:16 video and a concise caption.'},youtube:{limit:5000,types:['Video'],guide:'A video is required for YouTube publishing.'}};
function escapeHtml(value){const div=document.createElement('div');div.textContent=value||'';return div.innerHTML}function current(){return config[platform.value]||config.facebook}function feedback(field){let el=document.getElementById(`${field}-error`);if(!el){el=document.createElement('div');el.id=`${field}-error`;el.className='invalid-feedback';const input=document.getElementById(field);(input?.parentNode||document.getElementById('platform-picker')).append(el)}return el}function clearError(field){const input=document.getElementById(field);input?.classList.remove('is-invalid');if(field==='platform')document.getElementById('platform-picker').classList.remove('is-invalid');feedback(field).textContent=''}function setError(field,text){const input=document.getElementById(field);if(input)input.classList.add('is-invalid');if(field==='platform')document.getElementById('platform-picker').classList.add('is-invalid');feedback(field).textContent=text;return input||document.getElementById('platform-picker')}
function selectedAction(){return document.querySelector('[name="publish_option"]:checked')?.value||''}function validateStep(number){const checks={1:[['project_id',projectSelect.value,'Please select a project.']],2:[['platform',platform.value,'Please select a platform.']],3:[['social_page_id',target.value,'Please select an account or page.']],5:[['message',message.value.trim(),'Caption is required.']]};if(number===6){checks[6]=[['action',selectedAction(),'Please choose a publish option.']];if(selectedAction()==='schedule')checks[6].push(['scheduled_date',scheduledDate.value,'Schedule date is required.'],['scheduled_time',scheduledTime.value,'Schedule time is required.'],['timezone',timezone.value,'Timezone is required.']);if(selectedAction()==='schedule'&&scheduledDate.value&&scheduledTime.value&&timezone.value){const today=zoneDate(timezone.value);if(scheduledDate.value<today||scheduledDate.value===today&&scheduledTime.value<=zoneTime(timezone.value))checks[6].push(['scheduled_time',false,'You cannot schedule a post in the past. Please select a future date and time.'])}}const failures=(checks[number]||[]).filter(([,value])=>!value);(checks[number]||[]).forEach(([field,value])=>value&&clearError(field));failures.forEach(([field,,text])=>setError(field,text));return failures[0]?.[0]||null}
function show(newStep,validate=true){if(newStep>step&&validate){const invalid=validateStep(step);if(invalid){const field=document.getElementById(invalid)||document.querySelector('.wizard-platform-card');field.focus();field.scrollIntoView({behavior:'smooth',block:'center'});return}}step=newStep;document.querySelectorAll('.wizard-step').forEach(s=>s.classList.toggle('d-none',+s.dataset.step!==step));document.querySelectorAll('.wizard-progress-item').forEach(p=>p.classList.toggle('active',+p.dataset.progress<=step));document.getElementById('previous-step').classList.toggle('d-none',step===1);document.getElementById('next-step').classList.toggle('d-none',step===7);document.getElementById('submit-post').classList.toggle('d-none',step!==7);if(step===7)review();window.scrollTo({top:0,behavior:'smooth'})}
function renderDestinations(){const instagram=platform.value==='instagram',selected=target.value,pages=projectPages.filter(p=>p.provider===platform.value||(instagram&&p.provider==='facebook'&&p.instagram_business_id));target.innerHTML='<option value="">Select profile/page</option>'+pages.map(p=>`<option value="${p.id}">${instagram?`Facebook Page: ${escapeHtml(p.name)} → Instagram: @${escapeHtml(p.instagram_username||'Business Account')}`:escapeHtml(p.name)}</option>`).join('');if([...target.options].some(o=>o.value===selected))target.value=selected;document.getElementById('destination-label').innerHTML=`${instagram?'Facebook Page':'Page / Profile'} <span class="required-indicator">*</span>`;document.getElementById('destination-help').textContent=instagram?'Select the Facebook Page; its linked Instagram Business Profile will be selected automatically.':'Choose the connected destination for this post.'}
function renderPlatform(){const settings=current();document.querySelectorAll('.wizard-platform-card').forEach(card=>card.classList.toggle('active',card.dataset.platform===platform.value));document.getElementById('content-types').innerHTML=settings.types.map((type,index)=>`<label class="content-type-card"><input type="radio" name="content_type" value="${type.toLowerCase()}" ${index===0?'checked':''}><span><i class="bi bi-${type==='Video'||type==='Reel'?'play-circle':type==='Image'?'image':'chat-square-text'}"></i>${type}</span></label>`).join('');document.getElementById('platform-guidelines').innerHTML=`<strong>${platform.value?platform.value[0].toUpperCase()+platform.value.slice(1):'Platform'} guidelines</strong><p class="mb-0 mt-1">${settings.guide}</p>`;renderDestinations();updateCounter();updatePreview()}
function updateCounter(){const limit=current().limit,length=message.value.length,counter=document.getElementById('caption-counter');counter.textContent=`${length} / ${limit}`;counter.className=length>limit?'text-danger':'text-muted'}function updatePreview(){document.getElementById('preview-message').textContent=message.value||'Your caption will appear here.';document.getElementById('preview-dot').className=`platform-dot platform-${platform.value||'facebook'}`;const selected=target.options[target.selectedIndex];document.getElementById('preview-name').textContent=selected&&selected.value?selected.text.replace(/^Facebook Page: /,'').split(' → ')[0]:'Your profile'}function review(){const option=selectedAction(),selected=target.options[target.selectedIndex],files=[...media.files],schedule=option==='schedule'?`${scheduledDate.value||'No date'} at ${scheduledTime.value||'No time'} (${timezone.value})`:option==='publish'?'Publish immediately':'Save as a draft';document.getElementById('review-summary').innerHTML=[['Project',projectSelect.options[projectSelect.selectedIndex]?.text],['Platform',platform.value],['Destination',selected?.text],['Caption',message.value||'No caption'],['Media',files.length?`${files.length} file${files.length>1?'s':''}`:'No new media'],['Publish option',schedule]].map(([label,value])=>`<div><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}
function zoneParts(zone){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}function zoneDate(zone){try{const p=zoneParts(zone);return `${p.year}-${p.month}-${p.day}`}catch{return new Date().toISOString().slice(0,10)}}function zoneTime(zone){try{const p=zoneParts(zone);return `${p.hour}:${p.minute}`}catch{return new Date().toTimeString().slice(0,5)}}function updateScheduleLimits(){const today=zoneDate(timezone.value||'UTC');scheduledDate.min=today;scheduledTime.min=scheduledDate.value===today?zoneTime(timezone.value||'UTC'):''}function updateTimes(){try{const now=new Date(),zone=timezone.value||'UTC';document.getElementById('local-time').textContent=`${zone}: ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(now)}`;document.getElementById('utc-time').textContent=`UTC: ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(now)} UTC`;updateScheduleLimits()}catch(e){document.getElementById('local-time').textContent='Enter a valid IANA timezone.'}}
projectPages=Array.from(target.options).slice(1).map(o=>({id:o.value,provider:o.dataset.provider,name:o.textContent.trim(),instagram_business_id:o.dataset.instagram==='1',instagram_username:o.dataset.instagramUsername}));document.querySelectorAll('.wizard-platform-card').forEach(card=>card.addEventListener('click',()=>{platform.value=card.dataset.platform;clearError('platform');renderPlatform()}));projectSelect.addEventListener('change',async()=>{clearError('project_id');target.innerHTML='<option>Loading profiles/pages…</option>';const response=await fetch(`{{ route('posts.pages') }}?project_id=${encodeURIComponent(projectSelect.value)}`,{headers:{Accept:'application/json'}});projectPages=response.ok?await response.json():[];renderDestinations()});target.addEventListener('change',()=>{clearError('social_page_id');updatePreview()});message.addEventListener('input',()=>{clearError('message');updateCounter();updatePreview()});document.querySelectorAll('[data-insert]').forEach(button=>button.addEventListener('click',()=>{message.value+=`${message.value?' ':''}${button.dataset.insert}`;message.focus();updateCounter();updatePreview()}));media.addEventListener('change',()=>{const files=[...media.files],preview=document.getElementById('preview-media');document.getElementById('media-thumbnails').innerHTML=files.map(file=>`<span class="media-chip"><i class="bi bi-file-earmark"></i> ${escapeHtml(file.name)}</span>`).join('');if(files[0]?.type.startsWith('image/')){preview.style.backgroundImage=`url('${URL.createObjectURL(files[0])}')`;preview.classList.remove('d-none')}else preview.classList.add('d-none')});document.querySelectorAll('[name="publish_option"]').forEach(input=>input.addEventListener('change',()=>{action.value=input.value;document.getElementById('schedule-fields').classList.toggle('d-none',input.value!=='schedule');clearError('action')}));[scheduledDate,scheduledTime,timezone].forEach(input=>input.addEventListener('change',()=>{clearError(input.id);updateTimes()}));document.getElementById('next-step').addEventListener('click',()=>show(step+1));document.getElementById('previous-step').addEventListener('click',()=>show(step-1));form.addEventListener('submit',event=>{action.value=selectedAction();for(let number=1;number<=6;number++){const invalid=validateStep(number);if(invalid){event.preventDefault();show(number,false);const field=document.getElementById(invalid)||document.querySelector('.wizard-platform-card');field.focus();field.scrollIntoView({behavior:'smooth',block:'center'});return}}});renderPlatform();document.getElementById('schedule-fields').classList.toggle('d-none',selectedAction()!=='schedule');updateTimes();show(step,false);const firstInvalid=form.querySelector('.is-invalid');if(firstInvalid)setTimeout(()=>{firstInvalid.focus();firstInvalid.scrollIntoView({behavior:'smooth',block:'center'})},100);
</script>
@endpush
