@extends('layouts.app')

@php($editing = isset($post))
@section('title', $editing ? 'Edit Post' : 'Create Post')
@section('subtitle', 'A guided workflow for creating polished social content')

@section('content')
<form method="post" action="{{ $editing ? route('posts.update', $post) : route('posts.store') }}" enctype="multipart/form-data" id="post-wizard" novalidate>
    @csrf
    @if($editing) @method('PUT') @endif
    <input type="hidden" name="platform" id="platform" value="{{ old('platform', $post->platform ?? '') }}">

    <div class="wizard-progress mb-4" aria-label="Create post progress">
        @foreach(['Project','Platform','Destination','Content','Creative','Publish','Review'] as $number => $label)
            <div class="wizard-progress-item" data-progress="{{ $number + 1 }}"><span>{{ $number + 1 }}</span><strong>{{ $label }}</strong></div>
        @endforeach
    </div>

    <div class="wizard-shell">
        <section class="wizard-step" data-step="1">
            <div class="wizard-step-heading"><span>Step 1</span><h2>Select Project</h2><p>Choose the workspace this post belongs to.</p></div>
            <label class="form-label" for="project_id">Project</label>
            <select class="form-select form-select-lg" name="project_id" id="project_id" required><option value="">Select project</option>@foreach($projects as $item)<option value="{{ $item->id }}" @selected((int) old('project_id', $project?->id) === $item->id)>{{ $item->name }}</option>@endforeach</select>
        </section>

        <section class="wizard-step d-none" data-step="2">
            <div class="wizard-step-heading"><span>Step 2</span><h2>Select Platform</h2><p>Choose where you want this content to appear.</p></div>
            <div class="wizard-platform-grid" id="platform-picker">@foreach(['facebook'=>'Facebook','instagram'=>'Instagram','linkedin'=>'LinkedIn','twitter'=>'X (Twitter)','tiktok'=>'TikTok','youtube'=>'YouTube'] as $key => $name)<button type="button" class="wizard-platform-card" data-platform="{{ $key }}"><span class="platform-dot platform-{{ $key }}"></span><strong>{{ $name }}</strong><small>Publish to {{ $name }}</small></button>@endforeach</div>
        </section>

        <section class="wizard-step d-none" data-step="3">
            <div class="wizard-step-heading"><span>Step 3</span><h2>Select Page, Profile or Account</h2><p id="destination-help">Choose the connected destination for this post.</p></div>
            <label class="form-label" id="destination-label" for="social_page_id">Page / Profile</label>
            <select class="form-select form-select-lg" name="social_page_id" id="social_page_id"><option value="">Select profile/page</option>@foreach($pages as $page)<option value="{{ $page->id }}" data-provider="{{ $page->provider }}" data-instagram="{{ $page->instagram_business_id ? '1' : '0' }}" data-instagram-username="{{ $page->instagram_username }}" @selected((int) old('social_page_id', $post->social_page_id ?? 0) === $page->id)>{{ ucfirst($page->provider) }} - {{ $page->page_name }}{{ $page->instagram_username ? ' / @'.$page->instagram_username : '' }}</option>@endforeach</select>
        </section>

        <section class="wizard-step d-none" data-step="4">
            <div class="wizard-step-heading"><span>Step 4</span><h2>Select Content Type</h2><p>Only formats supported by the selected platform are shown.</p></div>
            <div class="content-type-grid" id="content-types"></div>
            <div class="guidelines-card mt-4" id="platform-guidelines"></div>
        </section>

        <section class="wizard-step d-none" data-step="5">
            <div class="wizard-step-heading"><span>Step 5</span><h2>Create Your Content</h2><p>Write your caption, add media, and check the live preview.</p></div>
            <div class="row g-4"><div class="col-lg-7"><label class="form-label d-flex justify-content-between" for="message">Caption <span id="caption-counter" class="text-muted"></span></label><textarea class="form-control composer-text" id="message" name="message" maxlength="63206" required>{{ old('message', $post->message ?? '') }}</textarea><div class="composer-tools"><button type="button" class="btn btn-light btn-sm" data-insert="#"># Hashtag</button><button type="button" class="btn btn-light btn-sm" data-insert="@">@ Mention</button></div><label class="form-label mt-4">Upload Media</label><div class="upload-zone"><i class="bi bi-cloud-arrow-up"></i><div><strong>Drop images or videos here</strong><span>JPG, PNG, WEBP, GIF, MP4, MOV, AVI, WEBM</span></div><input class="form-control" id="media" type="file" name="media[]" multiple accept="image/*,video/*"></div><div class="media-thumbnails mt-3" id="media-thumbnails">@if($editing) @foreach($post->media as $media)<span class="media-chip"><i class="bi bi-file-earmark"></i> {{ basename($media->path) }}</span>@endforeach @endif</div></div><div class="col-lg-5"><div class="live-preview"><div class="preview-label">Live preview</div><div class="preview-head"><span class="platform-dot" id="preview-dot"></span><strong id="preview-name">Your profile</strong></div><div id="preview-media" class="preview-media d-none"></div><p id="preview-message" class="mb-0 text-break">Your caption will appear here.</p></div></div></div>
        </section>

        <section class="wizard-step d-none" data-step="6">
            <div class="wizard-step-heading"><span>Step 6</span><h2>Select Publish Option</h2><p>Save it for later, schedule it, or publish immediately.</p></div>
            <div class="publish-option-grid"><label><input type="radio" name="publish_option" value="draft" checked><span><i class="bi bi-save"></i><strong>Save Draft</strong><small>Keep editing later</small></span></label><label><input type="radio" name="publish_option" value="schedule"><span><i class="bi bi-calendar-plus"></i><strong>Schedule</strong><small>Choose a future time</small></span></label><label><input type="radio" name="publish_option" value="publish"><span><i class="bi bi-send"></i><strong>Publish Now</strong><small>Send to the selected account</small></span></label></div>
            <div id="schedule-fields" class="schedule-fields d-none mt-4"><div class="row g-3"><div class="col-md-4"><label class="form-label">Date</label><input class="form-control" type="date" name="scheduled_date" value="{{ old('scheduled_date', isset($post?->scheduled_date) ? $post->scheduled_date->format('Y-m-d') : '') }}"></div><div class="col-md-4"><label class="form-label">Time</label><input class="form-control" type="time" name="scheduled_time" value="{{ old('scheduled_time', $post->scheduled_time ?? '') }}"></div><div class="col-md-4"><label class="form-label">Timezone</label><input class="form-control" id="timezone" list="timezone-options" name="timezone" value="{{ old('timezone', $post->timezone ?? auth()->user()->timezone ?? config('app.timezone')) }}" required><datalist id="timezone-options"><option value="UTC"><option value="America/New_York"><option value="America/Los_Angeles"><option value="Europe/London"><option value="Asia/Kolkata"><option value="Asia/Dubai"><option value="Asia/Singapore"></datalist></div></div><div class="time-card mt-3"><strong>Current time</strong><div id="local-time" class="small mt-1"></div><div id="utc-time" class="small"></div><p class="small text-muted mb-0 mt-2">All scheduled posts are stored internally in UTC and automatically published according to this timezone.</p></div></div>
        </section>

        <section class="wizard-step d-none" data-step="7">
            <div class="wizard-step-heading"><span>Step 7</span><h2>Review Summary</h2><p>Confirm the details before your post is saved or published.</p></div>
            <div class="review-summary" id="review-summary"></div>
        </section>

        <div class="wizard-footer"><button type="button" class="btn btn-outline-secondary d-none" id="previous-step">Back</button><button type="button" class="btn btn-primary" id="next-step">Continue</button><button type="submit" class="btn btn-primary d-none" id="submit-post">Finish</button></div>
    </div>
</form>
@endsection

@push('scripts')
<script>
const form=document.getElementById('post-wizard'),projectSelect=document.getElementById('project_id'),platform=document.getElementById('platform'),target=document.getElementById('social_page_id'),message=document.getElementById('message'),media=document.getElementById('media');let step=1,projectPages=[];
const config={facebook:{limit:63206,types:['Post','Image','Video','Reel'],guide:'Recommended image: 1200 × 630. Videos up to 10GB. Keep captions under 250 characters for best engagement.'},instagram:{limit:2200,types:['Image','Reel','Carousel'],guide:'Image: 1080 × 1080. Reels: 9:16. Caption limit: 2,200 characters. Use 3–10 hashtags.'},linkedin:{limit:3000,types:['Post','Image','Video'],guide:'Recommended image: 1200 × 627. Character limit: 3,000.'},twitter:{limit:280,types:['Post','Image','Video'],guide:'Standard posts support up to 280 characters.'},tiktok:{limit:2200,types:['Video'],guide:'Use 9:16 video and a concise caption.'},youtube:{limit:5000,types:['Video'],guide:'A video is required for YouTube publishing.'}};
function escapeHtml(value){const div=document.createElement('div');div.textContent=value||'';return div.innerHTML}function current(){return config[platform.value]||config.facebook}function valid(){if(step===1&&!projectSelect.value)return false;if(step===2&&!platform.value)return false;if(step===3&&!target.value)return false;return true}function show(newStep){if(newStep>step&&!valid()){(step===1?projectSelect:step===3?target:document.querySelector('.wizard-platform-card')).focus();return}step=newStep;document.querySelectorAll('.wizard-step').forEach(s=>s.classList.toggle('d-none',+s.dataset.step!==step));document.querySelectorAll('.wizard-progress-item').forEach(p=>p.classList.toggle('active',+p.dataset.progress<=step));document.getElementById('previous-step').classList.toggle('d-none',step===1);document.getElementById('next-step').classList.toggle('d-none',step===7);document.getElementById('submit-post').classList.toggle('d-none',step!==7);if(step===7)review();window.scrollTo({top:0,behavior:'smooth'})}
function renderDestinations(){const isInstagram=platform.value==='instagram',selected=target.value,pages=projectPages.filter(p=>p.provider===platform.value||(isInstagram&&p.provider==='facebook'&&p.instagram_business_id));target.innerHTML='<option value="">Select profile/page</option>'+pages.map(p=>`<option value="${p.id}">${isInstagram?`Facebook Page: ${escapeHtml(p.name)} → Instagram: @${escapeHtml(p.instagram_username||'Business Account')}`:escapeHtml(p.name)}</option>`).join('');if([...target.options].some(o=>o.value===selected))target.value=selected;document.getElementById('destination-label').textContent=isInstagram?'Facebook Page':'Page / Profile';document.getElementById('destination-help').textContent=isInstagram?'Select the Facebook Page; its linked Instagram Business Profile will be selected automatically.':'Choose the connected destination for this post.'}
function renderPlatform(){const settings=current();document.querySelectorAll('.wizard-platform-card').forEach(card=>card.classList.toggle('active',card.dataset.platform===platform.value));document.getElementById('content-types').innerHTML=settings.types.map((type,index)=>`<label class="content-type-card"><input type="radio" name="content_type" value="${type.toLowerCase()}" ${index===0?'checked':''}><span><i class="bi bi-${type==='Video'||type==='Reel'?'play-circle':type==='Image'?'image':'chat-square-text'}"></i>${type}</span></label>`).join('');document.getElementById('platform-guidelines').innerHTML=`<strong>${platform.value?platform.value[0].toUpperCase()+platform.value.slice(1):'Platform'} guidelines</strong><p class="mb-0 mt-1">${settings.guide}</p>`;renderDestinations();updateCounter();updatePreview()}
function updateCounter(){const limit=current().limit,length=message.value.length,counter=document.getElementById('caption-counter');counter.textContent=`${length} / ${limit}`;counter.className=length>limit?'text-danger':'text-muted'}function updatePreview(){document.getElementById('preview-message').textContent=message.value||'Your caption will appear here.';document.getElementById('preview-dot').className=`platform-dot platform-${platform.value||'facebook'}`;const selected=target.options[target.selectedIndex];document.getElementById('preview-name').textContent=selected&&selected.value?selected.text.replace(/^Facebook Page: /,'').split(' → ')[0]:'Your profile'}
function review(){const option=document.querySelector('[name="publish_option"]:checked').value,selected=target.options[target.selectedIndex],files=[...media.files];const schedule=option==='schedule'?`${form.scheduled_date.value||'No date'} at ${form.scheduled_time.value||'No time'} (${form.timezone.value})`:option==='publish'?'Publish immediately':'Save as a draft';document.getElementById('review-summary').innerHTML=[['Project',projectSelect.options[projectSelect.selectedIndex]?.text],['Platform',platform.value],['Destination',selected?.text],['Content type',document.querySelector('[name="content_type"]:checked')?.value],['Caption',message.value||'No caption'],['Media',files.length?`${files.length} file${files.length>1?'s':''}`:'No new media'],['Publish option',schedule]].map(([label,value])=>`<div><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}
projectPages=Array.from(target.options).slice(1).map(o=>({id:o.value,provider:o.dataset.provider,name:o.textContent.trim(),instagram_business_id:o.dataset.instagram==='1',instagram_username:o.dataset.instagramUsername}));document.querySelectorAll('.wizard-platform-card').forEach(card=>card.addEventListener('click',()=>{platform.value=card.dataset.platform;renderPlatform()}));projectSelect.addEventListener('change',async()=>{target.innerHTML='<option>Loading profiles/pages…</option>';const response=await fetch(`{{ route('posts.pages') }}?project_id=${encodeURIComponent(projectSelect.value)}`,{headers:{Accept:'application/json'}});projectPages=response.ok?await response.json():[];renderDestinations()});target.addEventListener('change',updatePreview);message.addEventListener('input',()=>{updateCounter();updatePreview()});document.querySelectorAll('[data-insert]').forEach(button=>button.addEventListener('click',()=>{message.value+=`${message.value?' ':''}${button.dataset.insert}`;message.focus();updateCounter();updatePreview()}));media.addEventListener('change',()=>{const files=[...media.files],preview=document.getElementById('preview-media');document.getElementById('media-thumbnails').innerHTML=files.map(file=>`<span class="media-chip"><i class="bi bi-file-earmark"></i> ${escapeHtml(file.name)}</span>`).join('');if(files[0]?.type.startsWith('image/')){preview.style.backgroundImage=`url('${URL.createObjectURL(files[0])}')`;preview.classList.remove('d-none')}else preview.classList.add('d-none')});document.querySelectorAll('[name="publish_option"]').forEach(input=>input.addEventListener('change',()=>document.getElementById('schedule-fields').classList.toggle('d-none',input.value!=='schedule'||!input.checked)));const timezone=document.getElementById('timezone');if(!timezone.value||timezone.value==='UTC')timezone.value=Intl.DateTimeFormat().resolvedOptions().timeZone||timezone.value;function updateTimes(){try{const now=new Date(),zone=timezone.value||'UTC';document.getElementById('local-time').textContent=`${zone}: ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(now)}`;document.getElementById('utc-time').textContent=`UTC: ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(now)} UTC`}catch(e){document.getElementById('local-time').textContent='Enter a valid IANA timezone.'}}timezone.addEventListener('change',updateTimes);document.getElementById('next-step').addEventListener('click',()=>show(step+1));document.getElementById('previous-step').addEventListener('click',()=>show(step-1));form.addEventListener('submit',()=>{const action=document.createElement('input');action.type='hidden';action.name='action';action.value=document.querySelector('[name="publish_option"]:checked').value;form.append(action)});renderPlatform();updateTimes();
</script>
@endpush
